name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  test-and-revert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm install puppeteer

      - name: Setup Chrome for testing
        run: echo "CHROME_BIN=$(npx puppeteer print-chromium-path)" >> $GITHUB_ENV

      - name: Run tests
        id: tests
        run: npm run test:ci
        continue-on-error: true

      - name: Revert push on test failure
        if: steps.tests.outcome == 'failure' && github.event_name == 'push'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git revert ${{ github.sha }} --no-edit
          git push origin main





